### ISSUE TITLE
Plugin upload percentage does not show 100% after upload is completed

### ISSUE THREAD

**Issue by 321github123** [OpenC3/cosmos#1453] opened 2024-08-05 18:24 UTC
First check out our main documentation site at [https://openc3.com](https://openc3.com).

**Describe the bug**
Plugin has been uploaded but percentage bar does not show 100%

**To Reproduce**

1. Upload plugin using Admin console

**Expected behavior**
After plugin upload has been complete, percentage bar shows 100%

**Screenshots**
![image](https://github.com/user-attachments/assets/5b3dc14f-42d6-410c-9db8-c1f36d9d3982)

**Environment (please complete the following information):**

- OS: Red Hat Enterprise Linux 8.10 (Ootpa)
- OpenC3 COSMOS Version 5.17.1 Enterprise
- Browser: Chrome

**Comment by jmthomas** [comment] 2024-08-06 16:47
duplicate of #1443

**Closed by jmthomas** 2024-08-06 16:47 UTC
Labels: duplicate
