### ISSUE TITLE
Add ability to search by item name only

### ISSUE THREAD

**Issue by 321github123** [OpenC3/cosmos#1302] opened 2024-05-28 17:54 UTC
First check out our main documentation site at [https://openc3.com](https://openc3.com).

**Is your feature request related to a problem? Please describe.**
Our uses are typically more familiar with telemetry items rather than the packet the item is in.

**Describe the solution you'd like**
Add ability to search by item only e.g. when using Data Viewer.

**Additional context**

**Comment by jmthomas** [comment] 2024-05-28 20:02
duplicate of #964

**Closed by jmthomas** 2024-05-28 20:02 UTC
Labels: duplicate
