### ISSUE TITLE
cmd display persistence

### ISSUE THREAD

**Issue by sunws4me** [OpenC3/cosmos#1329] opened 2024-06-11 21:10 UTC
CommandServer View would be nice if the cmds executed by a given user would persistence in that view.

after I execute cmd(s) via CommandServer, then switch to a different view and back to CommandServer the cmd(s) executed are gone.

**Comment by jmthomas** [comment] 2024-06-11 21:22
duplicate of #1175

**Closed by jmthomas** 2024-06-11 21:22 UTC
Labels: duplicate
