### ISSUE TITLE
Errors when opening files in script runner

### ISSUE THREAD

**Issue by mdpalme** [OpenC3/cosmos#1421] opened 2024-07-19 14:44 UTC
First check out our main documentation site at [https://openc3.com](https://openc3.com).

**Describe the bug**
Unable to open a previously edited file in script runner.
- Error: Failed to open <TargetName>/procedures/cfdp_test.rb*. AxiosError: Request failed with status code 500
- Network error: HTTP 500 - Internal Server Error

**To Reproduce**

1. Modifying an existing script (e.g. cfdp_test.rb) in script runner
2. Run the script
3. Some time later, after trying to access the file again, access will be prevented and the screenshot and errors below will be shown.
4. After some combination of saving the file, deleting the file out of targets_modified, and closing script runner it becomes possible to open the file again.

**Expected behavior**
I expect to be able to open, view, and edit the file again.

**Screenshots**
<img width="1442" alt="Screenshot 2024-07-19 082900" src="https://github.com/user-attachments/assets/7b8849f8-c862-4552-9837-b668230751d1">

**Environment (please complete the following information):**

- OS: Windows 11
- OpenC3 COSMOS Version 5.17.1
- Browser: Chrome Version 126.0.6478.128 (Official Build) (64-bit)

**Comment by jmthomas** [comment] 2024-07-19 16:59
This is not going to be easy to reproduce. If you see this again can you please go to the terminal and type `docker logs cosmos-openc3-cosmos-script-runner-api-1` and `docker logs cosmos-openc3-cosmos-cmd-tlm-api-1` and post any stack traces that you see? Thanks.

**Comment by jmthomas** [comment] 2024-08-29 14:19
Closing due to lack of information. I can not reproduce.

**Closed by jmthomas** 2024-08-29 14:19 UTC
Labels: triage
