### ISSUE TITLE
Uninstalling an Updated Plugin Does NOT Remove it

### ISSUE THREAD

**Issue by tsjordan-eng** [OpenC3/cosmos#940] opened 2023-11-17 18:14 UTC
**Describe the bug**

When a plugin has been updated several times (during the development stage), then the uninstallation doesn't remove the plugin, just the latest update. This is not expected behavior. Uninstalling should remove the plugin, not downgrade it.

**To Reproduce**

1. Install multiple updates to a plugin
2. Try uninstalling it--the plugin will remain

**Expected behavior**
Uninstalling the plugin should remove it completely, not downgrade it.

**Environment (please complete the following information):**

- OS: RHEL9, Podman
- OpenC3 COSMOS Version 5.11.3
- Browser: Edge

**Comment by ryanmelt** [comment] 2023-11-17 18:15
The plugin won't remain, but some older gem files might.  Is that what you are seeing?

**Comment by tsjordan-eng** [comment] 2023-11-17 21:20
We see the plugin and the gem disappear. Then both would reappear.

**Comment by ryanmelt** [comment] 2023-11-17 21:23
I'll see if I can recreate, but this feels like more of something custom you may be doing?
I can't think of a route that would reinstall an old plugin.   

Can you check the docker logs for the openc3-cosmos-cmd-tlm-api, and see if there are any errors there when this occurs?

**Comment by tsjordan-eng** [comment] 2023-11-20 22:01
Next time it happens I'll post them. I can't reproduce this at the moment.

**Comment by jmthomas** [comment] 2023-12-14 15:23
This could be related: During a recent training we observed the following error:
```
Stderr:
Error installing plugin: DEFAULT: openc3-cosmos-geosat-1.0.2.gem

RuntimeError : DEFAULT__openc3_targets:GEOSAT already exists at create
/usr/lib/ruby/gems/3.2.0/gems/openc3-5.12.1.pre.beta0/lib/openc3/models/model.rb:141:in `create'
/usr/lib/ruby/gems/3.2.0/gems/openc3-5.12.1.pre.beta0/lib/openc3/models/plugin_model.rb:232:in `block in install_phase2'
/usr/lib/ruby/gems/3.2.0/gems/openc3-5.12.1.pre.beta0/lib/openc3/config/config_parser.rb:217:in `parse_loop'
/usr/lib/ruby/gems/3.2.0/gems/openc3-5.12.1.pre.beta0/lib/openc3/config/config_parser.rb:217:in `parse_file'
/usr/lib/ruby/gems/3.2.0/gems/openc3-5.12.1.pre.beta0/lib/openc3/models/plugin_model.rb:226:in `install_phase2'
/openc3/bin/openc3cli:467:in `load_plugin'
/openc3/bin/openc3cli:649:in `<main>'
```

Seems like there is a race condition when upgrading a plugin such that the existing plugin doesn't get fully uninstalled before trying to install the new one. Or perhaps the uninstall is failing silently and the plugin remains (which would match this behavior).

**Comment by ryanmelt** [comment] 2024-01-07 19:32
I made some improvements to the upgrade process.  Closing until we see this again.

**Closed by ryanmelt** 2024-01-07 19:32 UTC
Labels: triage

**Comment by JTrulear93** [comment] 2024-01-11 18:11
I am having a similar issue. When I tried uninstalling a plugin, the gem file gets uninstalled, but the target remains. So now I cannot install a plugin with the same name. I'm sure this is unexpected behavior. Is this being worked on?

Plugins:
![image](https://github.com/OpenC3/cosmos/assets/122057610/ed618b8f-6782-4a26-abf8-89e070e74a24)

Targets:
![image](https://github.com/OpenC3/cosmos/assets/122057610/db41c631-00ea-4e3b-b2a9-ba95db08ea72)

As you can see, the number of targets does not match the number of gem files.

**Comment by ryanmelt** [comment] 2024-01-12 16:53
@JTrulear93 Did the uninstalls on the previous plugins fail?  If so looking at the eyeball icon in the plugins tab may provide more info.  

Also are you running 5.13?  I added some more checks to that release with this PR: https://github.com/OpenC3/cosmos/pull/986

**Comment by JTrulear93** [comment] 2024-01-16 15:33
The uninstalls did not fail. They succeeded (at least, there were no errors). And yes, I'm running v5.13, is there something special I need to do to fix this?

**Comment by ryanmelt** [comment] 2024-01-22 20:59
@JTrulear93 Looking at your output you are getting an error uninstalling relating to "unknown keyword: :disable_erb".  I don't know how that could happen unless you downgraded COSMOS versions.   Did you downgrade?

**Comment by JTrulear93** [comment] 2024-01-22 21:07
No, I did not downgrade. From what I can tell, I am still running v5.13

![image](https://github.com/OpenC3/cosmos/assets/122057610/3a79b8c3-2afd-4051-ae34-02aa783b11b6)

**Comment by ryanmelt** [comment] 2024-01-22 21:27
Ok.   Unfortunately its looks like we are eating the stacktrace so I can't get much more information.  I'll improve that in the 5.14.1 release tomorrow.   Once that is out please give it a try.

**Comment by JTrulear93** [comment] 2024-01-22 21:32
Okay, I'll try it again in the next release.

**Comment by lorenzo-gomez-windhover** [comment] 2024-07-31 20:48
Hello there,

Looks like I'm running into the same issue:



```
Stdout:
Loading new plugin: openc3-cosmos-cf-1.0.0.gem
{"name"=>"openc3-cosmos-cf-1.0.0.gem", "variables"=>{"ip"=>"127.0.0.1", "port_tm"=>"1235", "port_tc"=>"1234", "cfs_target_name"=>"CFS"}, "plugin_txt_lines"=>#<Array:1040>}
{"time":1722458481049146037,"@timestamp":"2024-07-31T20:41:21.049146Z","level":"INFO","container_name":"7765aab2c425","message":"Processing target definition in file '/tmp/d20240731-185-tma8z1/CFS/target.txt'","type":"log"}
{"time":1722458481072060670,"@timestamp":"2024-07-31T20:41:21.072060Z","level":"INFO","container_name":"7765aab2c425","message":"Configured microservice DEFAULT__COMMANDLOG__CFS","type":"log"}
{"time":1722458481072922991,"@timestamp":"2024-07-31T20:41:21.072922Z","level":"INFO","container_name":"7765aab2c425","message":"Configured microservice DEFAULT__DECOMCMDLOG__CFS","type":"log"}
{"time":1722458481073642231,"@timestamp":"2024-07-31T20:41:21.073642Z","level":"INFO","container_name":"7765aab2c425","message":"Configured microservice DEFAULT__PACKETLOG__CFS","type":"log"}
{"time":1722458481074367045,"@timestamp":"2024-07-31T20:41:21.074367Z","level":"INFO","container_name":"7765aab2c425","message":"Configured microservice DEFAULT__DECOMLOG__CFS","type":"log"}
{"time":1722458481075118792,"@timestamp":"2024-07-31T20:41:21.075118Z","level":"INFO","container_name":"7765aab2c425","message":"Configured microservice DEFAULT__DECOM__CFS","type":"log"}
{"time":1722458481075825438,"@timestamp":"2024-07-31T20:41:21.075825Z","level":"INFO","container_name":"7765aab2c425","message":"Configured microservice DEFAULT__REDUCER__CFS","type":"log"}
{"time":1722458481076560415,"@timestamp":"2024-07-31T20:41:21.076560Z","level":"INFO","container_name":"7765aab2c425","message":"Configured microservice DEFAULT__MULTI__CFS","type":"log"}
{"time":1722458481077833194,"@timestamp":"2024-07-31T20:41:21.077833Z","level":"INFO","container_name":"7765aab2c425","message":"Configured interface microservice DEFAULT__INTERFACE__CFS_INT","type":"log"}

Stderr:
Error installing plugin: DEFAULT: openc3-cosmos-cf-1.0.0.gem
Error : 
RuntimeError : DEFAULT__openc3_targets:CFS already exists at create
/usr/lib/ruby/gems/3.2.0/gems/openc3-5.17.1/lib/openc3/models/model.rb:146:in `create'
/usr/lib/ruby/gems/3.2.0/gems/openc3-5.17.1/lib/openc3/models/plugin_model.rb:250:in `block in install_phase2'
/usr/lib/ruby/gems/3.2.0/gems/openc3-5.17.1/lib/openc3/config/config_parser.rb:217:in `parse_loop'
/usr/lib/ruby/gems/3.2.0/gems/openc3-5.17.1/lib/openc3/config/config_parser.rb:217:in `parse_file'
/usr/lib/ruby/gems/3.2.0/gems/openc3-5.17.1/lib/openc3/models/plugin_model.rb:243:in `install_phase2'
/openc3/bin/openc3cli:487:in `load_plugin'
/openc3/bin/openc3cli:673:in `<main>'

/usr/lib/ruby/gems/3.2.0/gems/openc3-5.17.1/lib/openc3/config/config_parser.rb:472:in `parse_errors'
/usr/lib/ruby/gems/3.2.0/gems/openc3-5.17.1/lib/openc3/config/config_parser.rb:217:in `parse_loop'
/usr/lib/ruby/gems/3.2.0/gems/openc3-5.17.1/lib/openc3/config/config_parser.rb:217:in `parse_file'
/usr/lib/ruby/gems/3.2.0/gems/openc3-5.17.1/lib/openc3/models/plugin_model.rb:243:in `install_phase2'
/openc3/bin/openc3cli:487:in `load_plugin'
/openc3/bin/openc3cli:673:in `<main>'
```

Some more versioninfo:

```
CONTAINER ID   IMAGE                                              COMMAND                  CREATED        STATUS        PORTS                                                                                                                                        NAMES
7765aab2c425   openc3inc/openc3-cosmos-cmd-tlm-api:5.17.1         "/sbin/tini -- rails…"   25 hours ago   Up 25 hours   2901/tcp                                                                                                                                     cosmos-project-openc3-cosmos-cmd-tlm-api-1
0d5da754f5e4   openc3inc/openc3-operator:5.17.1                   "/sbin/tini -- ruby …"   25 hours ago   Up 25 hours   0.0.0.0:1235->1235/udp, :::1235->1235/udp                                                                                                    cosmos-project-openc3-operator-1
eafa5e19672b   openc3inc/openc3-cosmos-script-runner-api:5.17.1   "/sbin/tini -- rails…"   25 hours ago   Up 25 hours   2902/tcp                                                                                                                                     cosmos-project-openc3-cosmos-script-runner-api-1
be470171af6c   openc3inc/openc3-traefik:5.17.1                    "/entrypoint.sh trae…"   25 hours ago   Up 25 hours   127.0.0.1:2900->2900/tcp, 80/tcp, 127.0.0.1:2943->2943/tcp, 0.0.0.0:80->2900/tcp, :::80->2900/tcp, 0.0.0.0:443->2943/tcp, :::443->2943/tcp   cosmos-project-openc3-traefik-1
8cfb4d89bee1   openc3inc/openc3-redis:5.17.1                      "docker-entrypoint.s…"   25 hours ago   Up 25 hours   3680/tcp, 6379/tcp                                                                                                                           cosmos-project-openc3-redis-ephemeral-1
d19439647b69   openc3inc/openc3-minio:5.17.1                      "/usr/bin/docker-ent…"   25 hours ago   Up 25 hours   9000/tcp                                                                                                                                     cosmos-project-openc3-minio-1
4ebe44071783   openc3inc/openc3-redis:5.17.1                      "docker-entrypoint.s…"   25 hours ago   Up 25 hours   3680/tcp, 6379/tcp                                                                                                                           cosmos-project-openc3-redis-1

````

Thanks

**Comment by lorenzo-gomez-windhover** [comment] 2024-08-01 14:43
@ryanmelt Thanks for the quick response. Sorry for the lack of details--still getting familiar with COSMOS' workflows. I think what I did wrong was that I was trying to push a plugin with the same target name. I also realize that it looks like upgrading(by clicking on the upgrade option) the plugin might be the better thing to do, which is what works for me anyway.
